#!/usr/bin/python3
# Gets text that is ranked to be 100% Māori (from a text csv file output by hiki_niupepa_kupu) and saves it to a text file.

import re
import csv
from taumahi import *


def hiki_rau_ōrau(perehitanga_kōnae_ingoa, perehitanga_kōnae_ingoa_hou):
    # Writes formatted text from the input csv (an output of hiki_niupepa_kupu) which meet the criteria of ōrau == 100 to the output file.
    # Prints aspects from the row it has written, so the user can see how far through the csv the process is.

    with open(perehitanga_kōnae_ingoa, 'r') as kuputohu_kōnae, open(perehitanga_kōnae_ingoa_hou, 'w') as kupu_kōnae:
        kaipānui = csv.reader(kuputohu_kōnae)
        # Skip the header
        next(kaipānui)
        for rārangi in kaipānui:
            if float(rārangi[8]) == 100.00:
                kupu_kōnae.write(rārangi[9] + "\n")
                print(rārangi[:4])
        kuputohu_kōnae.close()
        kupu_kōnae.close()


def matua():
    whakatukai = argparse.ArgumentParser()
    whakatukai.add_argument(
        '--input', '-i', help="Input csv file to be sorted")
    whakatukai.add_argument(
        '--output', '-o', help="Output text file where sorted input file is to be stored")
    whakatukai.add_argument(
        '--rewrite', '-r', help="Input file to be sorted and saved under the same name")
    kōwhiri = whakatukai.parse_args()

    if kōwhiri.rewrite:
        perehitanga_kōnae_ingoa = perehitanga_kōnae_ingoa_hou = kōwhiri.rewrite

    else:
        perehitanga_kōnae_ingoa = kōwhiri.input if kōwhiri.input else 'perehitanga_kuputohu.csv'
        perehitanga_kōnae_ingoa_hou = kōwhiri.output if kōwhiri.output else 'tauira.txt'

    hiki_rau_ōrau(perehitanga_kōnae_ingoa, perehitanga_kōnae_ingoa_hou)


if __name__ == '__main__':
    matua()
