#!/usr/bin/python3
# Updates percentage of Māori words from an existing text file output by ______ without having to take from the internet again. Intended for when the taumahi module is updated.

import csv
import argparse
from taumahi import *
from tau import *


def whakahāngai_kōnae(perehitanga_kōnae_ingoa, perehitanga_kōnae_ingoa_hou):
    # Updates the Māori percentage estimate for the raw text in an existing csv for text scraped from the Māori newspaper website

    with open(perehitanga_kōnae_ingoa, 'r') as kōnae:
        kōnae_tūtira = list(csv.reader(kōnae))
        kōnae.close()

    with open(perehitanga_kōnae_ingoa_hou, 'w') as kōnae:
        perehitanga_kuputohu = csv.writer(kōnae)
        perehitanga_kuputohu.writerow(kōnae_tūtira[0])
        for rārangi in kōnae_tūtira[1:]:
            kupu = rārangi[9]
            kupu = rīwhi_tauriterite('((?!\d{4,})(£?([1-9]\d{0,2}[,\/‘’\'\".][ ]?)(\d{3}[,\/‘’\'\".][ ]?)*\d{3}([.,]{2}\d{1,2}){1,2}))', pakaru_moni, kupu, 1)
            kupu = rīwhi_tauriterite('(£?(\d[,\/‘’\'\".]?[ ]?)+ ?l\.? ?( ?\d+ ?[ds]\.? ?){0,2})', pakaru_moni, kupu, 2)
            kupu = rīwhi_tauriterite('((?!\d{4,})(£?([1-9]\d{0,2}[,\/‘’\'\".][ ]?)(\d{3}[,\/‘’\'\".][ ]?)*\d{3}( ?\d+ ?[ds]\.? ?){1,2}))', pakaru_moni, kupu, 3)
            kupu = rīwhi_tauriterite('(£?([1-9]\d*([.,]{2}\d{1,2}){1,2}))', pakaru_moni, kupu, 4)
            kupu = rīwhi_tauriterite('((?!\d{4,})(£?[1-9]\d*( ?\d+ ?[ds]\.? ?){1,2}))', pakaru_moni, kupu, 5)
            kupu = rīwhi_tauriterite('((\d{1,2}\/){1,2}\d{2})', rā_kupu, kupu)
            kupu = rīwhi_tauriterite('(\b\d{1,2} (Hanuere|Pepuere|Maehe|Apereira|Mei|Hune|Hurae|Akuhata|Hepetema|Oketopa|Noema|Tihema),? \d{4})', rā_kupu, kupu)
            kupu = rīwhi_tauriterite('((Hanuere|Pepuere|Maehe|Apereira|Mei|Hune|Hurae|Akuhata|Hepetema|Oketopa|Noema|Tihema) \d{1,2},? \d{4})', rā_kupu, kupu)
            kupu = rīwhi_tauriterite('((\d{1,2}\.){2}\d{1,2}( [ap]\.?m)?)', tāima_kupu, kupu)
            kupu = rīwhi_tauriterite('(£([1-9]\d{0,2}[,‘’\'\".][ ]?)(\d{3}[,\/‘’\'\".][ ]?)*\d{3})', pakaru_moni, kupu, 6)
            kupu = rīwhi_tauriterite('(([1-9]\d{0,2}[,‘’\'\".][ ]?)(\d{3}[,\/‘’\'\".][ ]?)*\d{3})', hōputu_tau, kupu)
            kupu = rīwhi_tauriterite('((\d{1,6}( ?/ ?|\.)){1,5}\d{1,5})', hautau_rānei_ira, kupu)
            kupu = rīwhi_tauriterite('(£(\d)+)', pakaru_moni, kupu, 7)
            kupu = rīwhi_tauriterite('((\d)+)', hōputu_tau, kupu)
            kupu = re.sub(r'[^A-Za-zĀĒĪŌŪāēīōū\s]', '', kupu)
            kupu = clean_whitespace(kupu)

            # Gets the new percentage
            ōrau = tiki_ōrau(kupu)
            # Writes the row with the new percentage in the place of the previous percentage
            perehitanga_kuputohu.writerow(
                rārangi[0:4] + list(ōrau) + [kupu] + list(reversed(rārangi[9:])))
            print(rārangi[0:4])
        kōnae.close()


def rīwhi_tauriterite(kimikimi, taumahi_ingoa, kōwae, number=0):
    a = kōwae
    ngā_whakataki_tūtira = re.compile(kimikimi).findall(kōwae)
    for ngā_whakataki in ngā_whakataki_tūtira:
        whakataki = ngā_whakataki[0].strip()
        kupu = " " + taumahi_ingoa(whakataki) + " "
        kōwae = re.compile(whakataki).sub(kupu, kōwae)
    if a != kōwae:
        pass
        #print(taumahi_ingoa.__name__)
    return kōwae


def matua():
    whakatukai = argparse.ArgumentParser()
    whakatukai.add_argument(
        '--input', '-i', help="Input csv file to be sorted")
    whakatukai.add_argument(
        '--output', '-o', help="Output text file where sorted input file is to be stored")
    whakatukai.add_argument(
        '--rewrite', '-r', help="Input file to be sorted and saved under the same name")
    kōwhiri = whakatukai.parse_args()

    if kōwhiri.rewrite:
        perehitanga_kōnae_ingoa = perehitanga_kōnae_ingoa_hou = kōwhiri.rewrite

    else:
        perehitanga_kōnae_ingoa = kōwhiri.input if kōwhiri.input else 'perehitanga_kōnae.csv'
        perehitanga_kōnae_ingoa_hou = kōwhiri.output if kōwhiri.output else 'perehitanga_kuputohu_no_numbers.csv'

    whakahāngai_kōnae(perehitanga_kōnae_ingoa, perehitanga_kōnae_ingoa_hou)


if __name__ == '__main__':
    matua()
